### ISSUE TITLE
[M1] Convert CSV files to SQL scripts

### ISSUE THREAD

**Issue by dcmnhb** [RMIT-Vietnam-Teaching/T01HN-COSC3056-2024A#3]
Historical temperature data files on Canvas are provided in CSV format. We will need to convert those into SQL scripts, which will then be used within Java files. Some available files in this template repository to consider:

- [VTPProcessCSV.java](https://github.com/RMIT-Vietnam-Teaching/T01HN-COSC3056-2024A/blob/main/src/main/java/helper/VTPProcessCSV.java)
- [everything in database/](https://github.com/RMIT-Vietnam-Teaching/T01HN-COSC3056-2024A/tree/main/database)
- [README also made a mention of these two](https://github.com/RMIT-Vietnam-Teaching/T01HN-COSC3056-2024A/blob/main/README.md#running-the-helper-program)

Some functions in the Java file should be changed as necessary to fit the new Relational Database Schema.

**Comment by kelewdnguyen** [comment]
Finished converting csv files to sql file
